/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operation.research;

import javax.swing.JOptionPane;

/**
 *
 * @author Ebad
 */
public class Choose extends javax.swing.JFrame {

    /**
     * Creates new form Choose
     */
    public Choose() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton_show_graph = new javax.swing.JButton();
        jButton_show_cpf = new javax.swing.JButton();
        jButton_main_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setTitle("Operation Research");
        jInternalFrame1.setVisible(true);

        jButton_show_graph.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jButton_show_graph.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_show_graph.setText("Show Graph");
        jButton_show_graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_graphActionPerformed(evt);
            }
        });

        jButton_show_cpf.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jButton_show_cpf.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_show_cpf.setText("Show CPF Points");
        jButton_show_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_cpfActionPerformed(evt);
            }
        });

        jButton_main_menu.setBackground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        jButton_main_menu.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jButton_main_menu.setText("Main Menu");
        jButton_main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_main_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_show_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_show_graph, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton_show_graph, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton_show_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton_main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_show_graphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_graphActionPerformed
        // TODO add your handling code here:

        //GeneralJournal frame = new GeneralJournal();
        //frame.setVisible(true);
        if (Data.size == 1) {
            Equation1graph graph = new Equation1graph("", "Operation ");
            graph.start();
        } else if (Data.size == 2) {

            Equation2graph graphs = new Equation2graph("", "Operation ");
            graphs.start();
        } else if (Data.size == 3) {
            Equation3graph graphs = new Equation3graph("", " ");
            graphs.start();
        }

    }//GEN-LAST:event_jButton_show_graphActionPerformed

    private void jButton_show_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_cpfActionPerformed
        // TODO add your handling code here:

        if (Data.size == 2 || Data.size == 3) {
            ShowCPF frame = new ShowCPF();
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "CPF point not available for this.");
        }

    }//GEN-LAST:event_jButton_show_cpfActionPerformed

    private void jButton_main_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_main_menuActionPerformed
        // TODO add your handling code here:

        Data.equations.clear();
        Data.listequations.clear();
        Data.matrixes.clear();
        Data.valueofz.clear();
        Data.gotz.clear();
        Data.thecpfpoint.clear();
        Data.points.clear();
        Data.size = 0;

        Mathe.listofmatrix.clear();
        Mathe.listofequations.clear();

        MainChoose equation = new MainChoose();
        equation.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_main_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Choose ch = new Choose();
                ch.setResizable(false);
                ch.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_main_menu;
    private javax.swing.JButton jButton_show_cpf;
    private javax.swing.JButton jButton_show_graph;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
