/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operation.research;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ebad
 */
public class MainEquation extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainEquation() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numberofequations = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        label_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operation Research");

        numberofequations.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberofequationsKeyPressed(evt);
            }
        });

        jLabel1.setText("No. of Equations");

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });
        NextButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NextButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(numberofequations, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(label_2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numberofequations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(NextButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(label_2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // TODO add your handling code here:

        String s = numberofequations.getText();
        if (s.length() == 0) {
            JOptionPane.showMessageDialog(this, "Please Enter Something.");
        } else {
            int number = 0;

            number = Integer.parseInt(s);

            if (number == 1) {
                dispose();
                Equation1 frame = new Equation1();
                frame.setVisible(true);
            } else if (number == 2) {
                dispose();
                Equation2 frame = new Equation2();
                frame.setVisible(true);
            } else if (number == 3) {
                dispose();
                Equation3 frame = new Equation3();
                frame.setVisible(true);
            } else {
                 JOptionPane.showMessageDialog(this, "Only available for 3 equation.");
            }
        }


    }//GEN-LAST:event_NextButtonActionPerformed

    private void NextButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NextButtonKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String s = numberofequations.getText();
            if (s.length() == 0) {
                JOptionPane.showMessageDialog(this, "Please Enter Something.");
            } else {
                int number = 0;

                number = Integer.parseInt(s);

                if (number == 1) {
                    dispose();
                    Equation1 frame = new Equation1();
                    frame.setVisible(true);
                } else if (number == 2) {
                    dispose();
                    Equation2 frame = new Equation2();
                    frame.setVisible(true);
                } else if (number == 3) {
                    dispose();
                    Equation3 frame = new Equation3();
                    frame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Only available for 3 equation.");
                }
            }
        }

    }//GEN-LAST:event_NextButtonKeyPressed

    private void numberofequationsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberofequationsKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             String s = numberofequations.getText();
            if (s.length() == 0) {
                 JOptionPane.showMessageDialog(this, "Please Enter Something.");
            } else {
                int number = 0;

                number = Integer.parseInt(s);

                if (number == 1) {
                    dispose();
                    Equation1 frame = new Equation1();
                    frame.setVisible(true);
                } else if (number == 2) {
                    dispose();
                    Equation2 frame = new Equation2();
                    frame.setVisible(true);
                } else if (number == 3) {
                    dispose();
                    Equation3 frame = new Equation3();
                    frame.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Only available for 3 equation.");
                }
            }
            
            
        }


    }//GEN-LAST:event_numberofequationsKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainEquation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                MainEquation mains = new MainEquation();
                mains.setResizable(false);
                mains.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_2;
    private javax.swing.JTextField numberofequations;
    // End of variables declaration//GEN-END:variables
}
