/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operation.research;

/**
 *
 * @author Ebad
 */
public class MainChoose extends javax.swing.JFrame {

    /**
     * Creates new form MainChoose
     */
    public MainChoose() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton_show_transpotation = new javax.swing.JButton();
        jButton_show_equation = new javax.swing.JButton();
        jButton_show_transpotation1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Operation Research");

        jInternalFrame1.setTitle("Operation Research");
        jInternalFrame1.setVisible(true);

        jButton_show_transpotation.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton_show_transpotation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_show_transpotation.setText("Northwest Corner Method");
        jButton_show_transpotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_transpotationActionPerformed(evt);
            }
        });

        jButton_show_equation.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton_show_equation.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_show_equation.setText("Graphical Method");
        jButton_show_equation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_equationActionPerformed(evt);
            }
        });

        jButton_show_transpotation1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton_show_transpotation1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_show_transpotation1.setText("Least Cost Method");
        jButton_show_transpotation1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_transpotation1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_show_equation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_show_transpotation, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addComponent(jButton_show_transpotation1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton_show_transpotation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jButton_show_transpotation1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton_show_equation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_show_transpotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_transpotationActionPerformed
        // TODO add your handling code here:

        dispose();
        North north = new North();
        north.setVisible(true);

    }//GEN-LAST:event_jButton_show_transpotationActionPerformed

    private void jButton_show_equationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_equationActionPerformed
        // TODO add your handling code here:

        dispose();
        MainEquation frame = new MainEquation();
        frame.setVisible(true);
    }//GEN-LAST:event_jButton_show_equationActionPerformed

    private void jButton_show_transpotation1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_show_transpotation1ActionPerformed
        // TODO add your handling code here:

        dispose();
        Least least = new Least();
        least.setVisible(true);


    }//GEN-LAST:event_jButton_show_transpotation1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainChoose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_show_equation;
    private javax.swing.JButton jButton_show_transpotation;
    private javax.swing.JButton jButton_show_transpotation1;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration//GEN-END:variables
}
