/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operation.research;

import javax.swing.table.DefaultTableModel;
import static operation.research.NorthGUISHOW.arrayme;

/**
 *
 * @author Ebad
 */
public class NorthGUISHOW2 extends javax.swing.JFrame {

    
    public static Problem arrayme[][] = new Problem[Data.row][Data.column];

    
    public NorthGUISHOW2() {
        initComponents();
         this.setResizable(false);
        arrayme = NorthwestProblem.temp;
        this.setLocationRelativeTo(null);
        jTable_north_show.setRowHeight(40);

        for (int i = 0; i < Data.row; i++) {
            for (int j = 0; j < Data.column; j++) {
                if (!arrayme[i][j].isCheck()) {
                    DefaultTableModel model = (DefaultTableModel) jTable_north_show.getModel();
                    model.setValueAt(arrayme[i][j].getValue() + " X " + arrayme[i][j].getAssvalue(), i, j);
                } else {
                    DefaultTableModel model = (DefaultTableModel) jTable_north_show.getModel();
                    model.setValueAt(arrayme[i][j].getValue()+"", i,j);
                }
            }
        }
        
        jTextField_answer.setText(Data.answerss+"");
        jTextField_equations.setText(NorthwestProblem.eq);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12as = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_north_show = new javax.swing.JTable();
        jTextField_equations = new javax.swing.JTextField();
        jTextField_answer = new javax.swing.JTextField();
        jButton_Done = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("NorthWest Corner Method");

        jLabel12as.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12as.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12as.setText("NorthWest Corner Method");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(28, 27));

        jTable_north_show.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable_north_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "                   1", "                   2", "                   3", "                   4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_north_show.setMinimumSize(new java.awt.Dimension(68, 48));
        jScrollPane1.setViewportView(jTable_north_show);

        jTextField_answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_answerActionPerformed(evt);
            }
        });

        jButton_Done.setText("Done");
        jButton_Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_equations, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jTextField_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jButton_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(jLabel12as, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12as, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField_equations, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_answer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Done, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_answerActionPerformed

    private void jButton_DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DoneActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_DoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NorthGUISHOW2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NorthGUISHOW2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NorthGUISHOW2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NorthGUISHOW2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               NorthGUISHOW2 sa =  new NorthGUISHOW2();
               sa.setResizable(false);
               sa.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Done;
    private javax.swing.JLabel jLabel12as;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_north_show;
    private javax.swing.JTextField jTextField_answer;
    private javax.swing.JTextField jTextField_equations;
    // End of variables declaration//GEN-END:variables
}
