package operation.research;

import javax.swing.JOptionPane;

public class NorthGUI2 extends javax.swing.JFrame {

    public static Problem array[][] = new Problem[Data.row][Data.column];

    public NorthGUI2() {
        initComponents();
        this.setLocationRelativeTo(null);
        jTable_north1.setRowHeight(30);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_north1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField_supply1 = new javax.swing.JTextField();
        jTextField_supply2 = new javax.swing.JTextField();
        jTextField_supply3 = new javax.swing.JTextField();
        jTextField_supply4 = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jTextField_demand1 = new javax.swing.JTextField();
        jTextField_demand2 = new javax.swing.JTextField();
        jTextField_demand3 = new javax.swing.JTextField();
        jTextField_demand4 = new javax.swing.JTextField();
        jButton_buttonext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NorthWest Corner Method");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NorthWest Corner Method");

        jScrollPane1.setMinimumSize(new java.awt.Dimension(28, 27));

        jTable_north1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "                   1", "                   2", "                   3", "                   4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_north1.setMinimumSize(new java.awt.Dimension(68, 48));
        jScrollPane1.setViewportView(jTable_north1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Supply");

        jTextField_supply1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supply1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_supply1ActionPerformed(evt);
            }
        });

        jTextField_supply2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_supply3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_supply3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_supply3ActionPerformed(evt);
            }
        });

        jTextField_supply4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel64.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel64.setText("Demand");

        jTextField_demand1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_demand2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField_demand3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_demand3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_demand3ActionPerformed(evt);
            }
        });

        jTextField_demand4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton_buttonext.setText("Next");
        jButton_buttonext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buttonextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_supply1)
                            .addComponent(jTextField_supply3)
                            .addComponent(jTextField_supply4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(jTextField_supply2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_demand1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_demand2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_demand3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_demand4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_buttonext, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_supply1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_supply2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_supply3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_supply4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_demand1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_demand2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_demand3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_demand4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jButton_buttonext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_supply1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_supply1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_supply1ActionPerformed

    private void jTextField_supply3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_supply3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_supply3ActionPerformed

    private void jTextField_demand3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_demand3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_demand3ActionPerformed

    private void jButton_buttonextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buttonextActionPerformed
        // TODO add your handling code here:

        String dem1, dem2, dem3, dem4, sup1, sup2, sup3, sup4;

        for (int i = 0; i < jTable_north1.getRowCount(); i++) {
            for (int j = 0; j < jTable_north1.getColumnCount(); j++) {
                array[i][j] = new Problem((double) jTable_north1.getModel().getValueAt(i, j), 0, false, false);
            }
        }

        double d1, d2, d3, d4;
        double s1, s2, s3, s4;

        dem1 = jTextField_demand1.getText();
        dem2 = jTextField_demand2.getText();
        dem3 = jTextField_demand3.getText();
        dem4 = jTextField_demand4.getText();

        d1 = Double.parseDouble(dem1);
        d2 = Double.parseDouble(dem2);
        d3 = Double.parseDouble(dem3);
        d4 = Double.parseDouble(dem4);

        sup1 = jTextField_supply1.getText();
        sup2 = jTextField_supply2.getText();
        sup3 = jTextField_supply3.getText();
        sup4 = jTextField_supply4.getText();

        s1 = Double.parseDouble(sup1);
        s2 = Double.parseDouble(sup2);
        s3 = Double.parseDouble(sup3);
        s4 = Double.parseDouble(sup4);

        double totaldemand;
        double totalsupply;

        totaldemand = d1 + d2 + d3 + d4;
        totalsupply = s1 + s2 + s3 + s4;

        if (totaldemand != totalsupply) {

            JOptionPane.showMessageDialog(this, "Demand not Equal to Supply.");
        } else {

            Data.demand.add(new Problem(d1));
            Data.demand.add(new Problem(d2));
            Data.demand.add(new Problem(d3));
            Data.demand.add(new Problem(d4));

            Data.supply.add(new Problem(s1));
            Data.supply.add(new Problem(s2));
            Data.supply.add(new Problem(s3));
            Data.supply.add(new Problem(s4));

            NorthwestProblem problem = new NorthwestProblem();

            dispose();

            ShowNORTHMENU menu = new ShowNORTHMENU();
            menu.setVisible(true);

        }

        /* NorthwestProblem problem = new NorthwestProblem();

        dispose();

        ShowNORTHMENU menu = new ShowNORTHMENU();
        menu.setVisible(true);
         */
    }//GEN-LAST:event_jButton_buttonextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NorthGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NorthGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NorthGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NorthGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NorthGUI2 gu = new NorthGUI2();
                gu.setResizable(false);
                gu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buttonext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_north1;
    private javax.swing.JTextField jTextField_demand1;
    private javax.swing.JTextField jTextField_demand2;
    private javax.swing.JTextField jTextField_demand3;
    private javax.swing.JTextField jTextField_demand4;
    private javax.swing.JTextField jTextField_supply1;
    private javax.swing.JTextField jTextField_supply2;
    private javax.swing.JTextField jTextField_supply3;
    private javax.swing.JTextField jTextField_supply4;
    // End of variables declaration//GEN-END:variables
}
