/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package operation.research;

/**
 *
 * @author Ebad
 */
public class ShowLEASTMENU extends javax.swing.JFrame {

    /**
     * Creates new form showLEASTMENU
     */
    public ShowLEASTMENU() {
        initComponents();
         this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jButton_show_solution = new javax.swing.JButton();
        jButton_show_main_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setResizable(true);
        jInternalFrame1.setTitle("Least Cost Method");
        jInternalFrame1.setVisible(true);

        jButton_show_solution.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton_show_solution.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_show_solution.setText("Show Solution");
        jButton_show_solution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_solutionActionPerformed(evt);
            }
        });

        jButton_show_main_menu.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        jButton_show_main_menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton_show_main_menu.setText("Main Menu");
        jButton_show_main_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_show_main_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton_show_main_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_show_solution, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                        .addContainerGap(92, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
                jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton_show_solution, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jButton_show_main_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addComponent(jInternalFrame1)
                        .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                        

    private void jButton_show_solutionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        if (Data.row == 3 && Data.column == 4) {
            LeastGUISHOW show = new LeastGUISHOW();
            show.setVisible(true);
        }

        if (Data.row == 4 && Data.column == 4) {
            LeastGUISHOW2 show = new LeastGUISHOW2();
            show.setVisible(true);
        }
        if (Data.row == 4 && Data.column == 3) {
            LeastGUISHOW3 show = new LeastGUISHOW3();
            show.setVisible(true);
        }
         if (Data.row == 3 && Data.column == 3) {
            LeastGUISHOW4 show = new LeastGUISHOW4();
            show.setVisible(true);
        }


    }

    private void jButton_show_main_menuActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

        Data.answerss = 0.0;
        Data.column = 0;
        Data.row = 0;
        Data.demand.clear();
        Data.supply.clear();
        LeastMethod.eq = "";

        dispose();
        MainChoose choose = new MainChoose();
        choose.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowLEASTMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowLEASTMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowLEASTMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowLEASTMENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowLEASTMENU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_show_main_menu;
    private javax.swing.JButton jButton_show_solution;
    private javax.swing.JInternalFrame jInternalFrame1;
    // End of variables declaration                   
}
